export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";


export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST ";
export const GET_DOCTORS_SUCCESS = " GET_DOCTORS_SUCCESS";
export const GET_DOCTORS_FAIL = "GET_DOCTORS_FAIL";

export const LIST_DOCTORS_REQUEST = "LIST_DOCTORS_REQUEST ";
export const LIST_DOCTORS_SUCCESS = " LIST_DOCTORS_SUCCESS";
export const LIST_DOCTORS_FAIL = "LIST_DOCTORS_FAIL";

export const GET_DOCTOR_REQUEST = "GET_DOCTOR_REQUEST ";
export const GET_DOCTOR_SUCCESS = " GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_FAIL = "GET_DOCTOR_FAIL";


